In [42]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier

In [30]:
# Import data

df = pd.read_csv('cleaned_spam.csv', encoding='latin-1')[['is_spam', 'sms']]
df.head(10)

is_spam                                                sms
0        1  go jurong point crazy available bugis n great ...
1        1                          ok lar joking wif you oni
2        0  free entry wkly comp win fa cup final tkts st ...
3        1            you dun say early hor you c already say
4        1              nah I think go usf live around though
5        0  freemsg hey darle week word back like fun stil...
6        1  even brother like speak I treat I like aids pa...
7        1  per request melle melle oru minnaminunginte nu...
8        0  winner value network customer select receivea ...
9        0  mobile month you r entitle update late colour ...

Vocabulary:  ['aa' 'aah' 'aaniye' ... 'zouk' 'zs' 'zyada']
TF-IDF Matrix:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 
 Shape: (5564, 7338)


In [38]:
# Naive Bayes Classifier

mnb = MultinomialNB()

mnb.fit(X_train_vectorized, y_train)

y_pred = mnb.predict(X_test_vectorized)

# Evaluation
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('\nClassification Report:\n', classification_report(y_test, y_pred))

Confusion Matrix:
 [[100  41]
 [  0 972]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.71      0.83       141
           1       0.96      1.00      0.98       972

    accuracy                           0.96      1113
   macro avg       0.98      0.85      0.90      1113
weighted avg       0.96      0.96      0.96      1113



In [ ]:
# New classifier : random forest

rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train_vectorized, y_train)
y_pred = rfc.predict(X_test_vectorized)
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('\nClassification Report:\n', classification_report(y_test, y_pred))


Confusion Matrix:
 [[119  22]
 [  1 971]]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.84      0.91       141
           1       0.98      1.00      0.99       972

    accuracy                           0.98      1113
   macro avg       0.98      0.92      0.95      1113
weighted avg       0.98      0.98      0.98      1113

